name: Update euribor data

concurrency:
  group: "update"
  cancel-in-progress: true

on:
  workflow_dispatch:

  schedule:
    # Runs "At 17:00." (see https://crontab.guru)
    - cron: '0 17 * * *'

jobs:
  update:
    runs-on: ubuntu-22.04
    steps:
      - name: 'What time is it?'
        id: time
        run: |
          echo "now=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT
          echo "prettynow=$(date +'%c %Z')" >> $GITHUB_OUTPUT
      - name: Prepare runtime
        run: sudo apt update && sudo apt install python3 -y
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0
      - name: Scrape euribor info
        run: bash ./scrape.sh
      - name: Check meaningful changes in assets/site/data.js
        id: change
        run: |
          if [ -n "$(git status -s site/assets/data.js)" ] ; then
            echo "presence=true" | tee $GITHUB_OUTPUT
          else
            echo "No meaningful edits"
          fi
      - name: Pull Request
        if: ${{ steps.change.outputs.presence == 'true' }}
        uses: peter-evans/create-pull-request@v4
        with:
          branch: update-data
          title:          "[${{ steps.time.outputs.prettynow }}] update EURIBOR/EURIS data"
          commit-message: "[${{ steps.time.outputs.prettynow }}] update EURIBOR/EURIS data"
          body:           "Scraping from https://www.euribor.it/ - checked at ${{ steps.time.outputs.prettynow }}"
          delete-branch: true
          labels: patch
